# Generated by Django 5.1.2 on 2024-11-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cpu', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=63, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer')),
            ],
        ),
    ]
