# Generated by Django 5.1.2 on 2024-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
