# Generated by Django 5.1.2 on 2024-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_manufacturer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('0', 'کارکرده'), ('1', 'آکبند')], max_length=1, null=True),
        ),
    ]
